AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for Backup and Disaster Recovery

Resources:
  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'my-backup-bucket-${AWS::AccountId}-${AWS::Region}'

  BackupMonitorFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/lambda_exec_role  # Replace with your IAM Role ARN
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          from datetime import datetime

          s3_client = boto3.client('s3')

          def lambda_handler(event, context):
              bucket_name = os.environ['BUCKET_NAME']
              backup_time = datetime.now().isoformat()
              print(f"Backup triggered for bucket: {bucket_name} at {backup_time}")
              return {
                  'statusCode': 200,
                  'body': json.dumps('Backup triggered!')
              }
      Runtime: python3.8
      Environment:
        BUCKET_NAME: !Ref BackupBucket

